In [0]:
------------------------------ TABLE FORMATION ------------------------------
drop table if exists people;
drop table if exists relations;

create table people (
  id int primary key not null,
  name varchar(20),
  gender char(2)
);

create table relations (
  c_id int,
  p_id int,
  constraint fk_child foreign key (c_id) references people(id),
  constraint fk_parent foreign key (p_id) references people(id)
);

insert into people (id, name, gender)
values
    (107,'Days','F'),
    (145,'Hawbaker','M'),
    (155,'Hansel','F'),
    (202,'Blackston','M'),
    (227,'Criss','F'),
    (278,'Keffer','M'),
    (305,'Canty','M'),
    (329,'Mozingo','M'),
    (425,'Nolf','M'),
    (534,'Waugh','M'),
    (586,'Tong','M'),
    (618,'Dimartino','M'),
    (747,'Beane','M'),
    (878,'Chatmon','F'),
    (904,'Hansard','F');

insert into relations(c_id, p_id)
values
    (145, 202),
    (145, 107),
    (278,305),
    (278,155),
    (329, 425),
    (329,227),
    (534,586),
    (534,878),
    (618,747),
    (618,904);
------------------------------------------------------------------------------------------

/*
Q1: 
We have two tables people and relations. The people table contains the details of each individual and the relations table contains the parent-child relationship between two individuals.
*/

-- Ans:
-- Method 1: Using CASE WHEN
select r.c_id, pe.name,
max(case when p.gender = 'F' then p.name end) as mother,
max(case when p.gender = 'M' then p.name end) as father
from relations as r
join people as p
on p.id = r.p_id
left join people as pe
on pe.id = r.c_id
group by r.c_id, pe.name;



-- Method 2: Using CTEs
with mother as (
select r.c_id, p.name as mother
from relations as r
join people as p
on p.id = r.p_id and p.gender = 'F'
),
father as (
select r.c_id, p.name as father
from relations as r
join people as p
on p.id = r.p_id and p.gender = 'M'
)
select p.name, m.mother, f.father
from mother as m
join father as f
on m.c_id = f.c_id
inner join people as p
on p.id = m.c_id;