In [0]:
------------------------------ TABLE FORMATION ------------------------------
drop table if exists movies;
drop table if exists reviews;

CREATE TABLE movies (
    id INT PRIMARY KEY,
    genre VARCHAR(50),
    title VARCHAR(100)
);

-- Create reviews table
CREATE TABLE reviews (
    movie_id INT,
    rating DECIMAL(3,1),
    FOREIGN KEY (movie_id) REFERENCES movies(id)
);

-- Insert sample data into movies table
INSERT INTO movies (id, genre, title) VALUES
(1, 'Action', 'The Dark Knight'),
(2, 'Action', 'Avengers: Infinity War'),
(3, 'Action', 'Gladiator'),
(4, 'Action', 'Die Hard'),
(5, 'Action', 'Mad Max: Fury Road'),
(6, 'Drama', 'The Shawshank Redemption'),
(7, 'Drama', 'Forrest Gump'),
(8, 'Drama', 'The Godfather'),
(9, 'Drama', 'Schindler''s List'),
(10, 'Drama', 'Fight Club'),
(11, 'Comedy', 'The Hangover'),
(12, 'Comedy', 'Superbad'),
(13, 'Comedy', 'Dumb and Dumber'),
(14, 'Comedy', 'Bridesmaids'),
(15, 'Comedy', 'Anchorman: The Legend of Ron Burgundy');

-- Insert sample data into reviews table
INSERT INTO reviews (movie_id, rating) VALUES
(1, 4.5),
(1, 4.0),
(1, 5.0),
(2, 4.2),
(2, 4.8),
(2, 3.9),
(3, 4.6),
(3, 3.8),
(3, 4.3),
(4, 4.1),
(4, 3.7),
(4, 4.4),
(5, 3.9),
(5, 4.5),
(5, 4.2),
(6, 4.8),
(6, 4.7),
(6, 4.9),
(7, 4.6),
(7, 4.9),
(7, 4.3),
(8, 4.9),
(8, 5.0),
(8, 4.8),
(9, 4.7),
(9, 4.9),
(9, 4.5),
(10, 4.6),
(10, 4.3),
(10, 4.7),
(11, 3.9),
(11, 4.0),
(11, 3.5),
(12, 3.7),
(12, 3.8),
(12, 4.2),
(13, 3.2),
(13, 3.5),
(13, 3.8),
(14, 3.8),
(14, 4.0),
(14, 4.2),
(15, 3.9),
(15, 4.0),
(15, 4.1);

------------------------------------------------------------------------------------------

/*
Q1:  Movie Streaming Service Genre Ranking:
During the development of a movie streaming service, a query is needed to return a list of movie genres and the best movie in that genre based on the maximum average review rating.

The result should have the following columns: genre | title | stars.
- genre-genre name
- title-movie title
- stars-rating of the movie in stars format:
  - Record format is a repeating number of stars from 1 to 5, which is the average rating of reviews rounded to the nearest whole number

The result should be sorted in ascending order by genre.
*/

-- Ans1:
-- Method 1: 

select * from movies;
select * from reviews;


with cte as
(
select m.*, r.*,
avg(r.rating) over(partition by m.title) as avg_rating
from reviews as r
join movies as m
on r.movie_id = m.id
)
select genre, max(title) as title, round(max(avg_rating),0) as avg_rating_within_genre,
repeat('*', cast(round(avg_rating, 0) as int)) as stars
from cte
group by genre, repeat('*', cast(round(avg_rating, 0) as int));


-- Method 2:
with cte as (
select m.genre, m.title, avg(r.rating) as avg_rating,
ROW_NUMBER() over (partition by m.genre order by avg(r.rating) desc) as rn
from movies m
inner join reviews r on m.id=r.movie_id
group by m.genre, m.title
)
select genre, title, round(avg_rating, 0) as avg_rating,
repeat('*', round(avg_rating, 0)) as stars
from cte
where rn=1;